spring:
  cache:
    type: redis
  session:
    storage-type: redis
  redis:
    cluster:
      nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006,127.0.0.1:7007



#spring:
#  cache:
#    type: redis
#  session:
#    storage-type: redis
#  redis:
#    host: localhost
#    port: 6379

#   client에서 sentinel로 접속하는 방법
#spring:
#  cache:
#    type: redis
#  session:
#    storage-type: redis
#  redis:
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381


