spring:
  application:
    name: api-server

server:
  port: 18080

# Optional: Additional configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
